name: Test and lint

on: [push]

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 21]

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

      - run: pnpm lint
